news:
    resource:
        path: ../src/News/Controller/
        namespace: App\News\Controller
    type: attribute

user:
    resource:
        path: ../src/User/Controller/
        namespace: App\User\Controller
    type: attribute

notifications:
    resource:
        path: ../src/Notifications/Controller/
        namespace: App\Notifications\Controller
    type: attribute
