# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: false # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Controller\NewsController:
    arguments:
      - '@App\Repository\NewsRepository'
      - '@App\Services\Helpers'
    tags:
      - 'controller.service_arguments'

  App\Controller\AuthController:
    arguments:
      - '@App\Repository\UserRepository'
      - '@App\Repository\AuthCodeRepository'
      - '@Lexik\Bundle\JWTAuthenticationBundle\Services\JWTTokenManagerInterface'
      - '@App\Telegram\Services\TelegramBotService'
      - '@doctrine.orm.entity_manager'
      - '@App\Services\Helpers'
      - '@security.helper'
      - '@messenger.bus.default'
    tags:
      - 'controller.service_arguments'

  App\Controller\UserController:
    arguments:
      - '@App\Repository\UserRepository'
      - '@App\Services\Helpers'
    tags:
      - 'controller.service_arguments'

  App\Telegram\Services\TelegramBotService:
    arguments:
      - '%env(TELEGRAM_BOT_TOKEN)%'
      - '%env(TELEGRAM_GROUP_ID)%'
      - '@eight_points_guzzle.client.custom_client'
      - '@App\Services\Helpers'

  App\Services\NewsDownloader:
    arguments:
    - '%env(NEWS_API_KEY)%'
    - '@eight_points_guzzle.client.custom_client'
    - '@doctrine.orm.entity_manager'

  App\Command\NewsDownloadCommand:
    arguments:
    - '@App\Services\NewsDownloader'

  App\Repository\NewsRepository:
    arguments:
    - '@Doctrine\Persistence\ManagerRegistry'

  App\Repository\UserRepository:
    arguments:
    - '@Doctrine\Persistence\ManagerRegistry'

  App\Repository\AuthCodeRepository:
    arguments:
    - '@Doctrine\Persistence\ManagerRegistry'

  App\Telegram\Messages\TelegramNotificationHandler:
    arguments:
    - '@App\Telegram\Services\TelegramBotService'
    - '@logger'
    tags:
    - 'messenger.message_handler'
