services:
  nginx:
    image: nginx:1.27
    container_name: ${PROJECT_NAME}-nginx
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/.output/public:/var/www/
      - php-socket:/var/run/php
    depends_on:
      - php

  php:
    build:
      dockerfile: .docker/php/Dockerfile
    container_name: ${PROJECT_NAME}-php
    depends_on:
      - mysql
      - rabbitmq
      - redis
    volumes:
      - ./.docker/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./backend/:/app
      - php-socket:/var/run/php

  node:
    build:
      dockerfile: .docker/node/Dockerfile
    container_name: ${PROJECT_NAME}-node
 
  mysql:
    image: mysql:9
    container_name: ${PROJECT_NAME}-mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  rabbitmq:
    image: rabbitmq:4-management
    container_name: ${PROJECT_NAME}-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:8
    container_name: ${PROJECT_NAME}-redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USER: ${REDIS_USER}
      REDIS_USER_PASSWORD: ${REDIS_USER_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data

volumes:
  mysql-data:
    driver: local
  php-socket:
    driver: local
