framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            telegram_notifications:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%/telegram_notifications"
                options:
                    exchange:
                        name: telegram_notifications
                        type: direct
                    queues:
                        telegram_notifications: ~

        routing:
            App\Telegram\Messages\TelegramNotification: telegram_notifications

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
